kind: pipeline
name: default

workspace:
  base: /go
  path: appsrc/

steps:
  - name: fetch
    image: docker:git
    when:
      event:
        - tag
    commands:
        - git fetch --tags

  - name: ui
    image: node
    when:
      event:
        - tag
    commands:
      - cd ui
      - yarn install
      - yarn build

  - name: build
    image: cld9x/goreleaser-xcgo:latest
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    when:
      event:
        - tag
    commands:
      - goreleaser --skip-validate --rm-dist

  - name: docker
    image: plugins/docker:18.09
    when:
      event:
        - tag
    settings:
      username:
        from_secret: DOCKER_LOGIN
      password:
        from_secret: DOCKER_PASSWORD
      repo: cld9x/xbvr
      auto_tag: true
      build_args: DRONE_TAG="${DRONE_TAG}"
