kind: pipeline
name: default

workspace:
  base: /go
  path: appsrc/

steps:
  - name: fetch
    image: docker:git
    when:
      event:
        - tag
    commands:
        - git fetch --tags

  - name: ui
    image: node
    when:
      event:
        - tag
    commands:
      - cd ui
      - yarn install
      - yarn build

  - name: build
    image: cld9x/goreleaser-xcgo:latest
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      DOCKER_LOGIN:
        from_secret: DOCKER_LOGIN
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    when:
      event:
        - tag
    commands:
      - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_LOGIN --password-stdin
      - goreleaser --skip-validate --rm-dist
